version: 2.1
jobs:
  ios-build:
    macos:
      xcode: "14.3.1"
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install Bundler
          command: gem install bundler
      - run:
          name: Install dependencies
          command: bundle install
      - run:
          name: Fastlane build
          command: bundle exec fastlane build
      - store_artifacts:
          path: build
          destination: ios-build
workflows:
  ios-build-workflow:
    jobs:
      - ios-build